"""
GENERATED BUILD ASSET - DO NOT EDIT MANUALLY.

The INDEX. Section line ranges transcribed verbatim from each document's
`*_index.md`, keyed by DOCUMENT FILE so two views of one document share
one table.

These ranges are NOT recomputed from the documents - Context Compass's
index is the authority and this is a transcription of it. The only
normalisation is stripping the markdown backticks the graph index wraps
its source paths in.

Imported LAZILY, on the first `index()` or `get()`. Ranges are 1-based
and inclusive on both ends, exactly as the source index states them.

Regenerate with:
    python src/melder/_build_assets/_build_asset_runner.py
"""

BUILT_FOR_VERSION = "0.2.79"
TABLE_COUNT = 3
SECTION_COUNT = 787

SECTIONS = {
    'src_architecture.md': (
        ('Metadata', 3, 9),
        ('Scope and Intent', 10, 32),
        ('Indexing', 33, 115),
        ('Indexing > Verifying the `path:line` citations in this document', 50, 115),
        ('DO NOT ASSUME / Unknowns Gate', 116, 139),
        ('Unknowns', 140, 203),
        ('System Context (C4)', 204, 219),
        ('Glossary and Core Terms', 220, 311),
        ('System Boundary and External Interfaces', 312, 473),
        ('Architecture Summary (C4)', 474, 505),
        ('Entrypoints and Runtime Guardrails', 506, 549),
        ('Boot and Configuration Sequence', 550, 626),
        ('Data Flows and Sequences', 627, 835),
        ('Data Flows and Sequences > Sequence: Import to Ready', 628, 634),
        ('Data Flows and Sequences > Sequence: Spellbook Initialization', 635, 641),
        ('Data Flows and Sequences > Sequence: Bind Spell', 642, 656),
        ('Data Flows and Sequences > Sequence: Conjure Conduit', 657, 688),
        ('Data Flows and Sequences > Sequence: Meld Resolution', 689, 711),
        ('Data Flows and Sequences > Sequence: Meld-Time Validation Gate', 712, 723),
        ('Data Flows and Sequences > Sequence: Create Lesser Conduit', 724, 734),
        ('Data Flows and Sequences > Sequence: Upgrade Lesser to Normal', 735, 748),
        ('Data Flows and Sequences > Sequence: Link and Sever Conduits', 749, 758),
        ('Data Flows and Sequences > Sequence: Transfer Spell Ownership', 759, 768),
        ('Data Flows and Sequences > Sequence: SpellIndex Mutation Entry', 769, 798),
        ('Data Flows and Sequences > Sequence: Change-Control Revalidation', 799, 807),
        ('Data Flows and Sequences > Sequence: SpellSpace Usage', 808, 812),
        ('Data Flows and Sequences > Sequence: Cleanup', 813, 835),
        ('Runtime Type Names (Concrete, No Interface Layer)', 836, 862),
        ('Extension Points', 863, 873),
        ('Operational Invariants', 874, 1261),
        ('Failure Modes and Error Paths', 1262, 1354),
        ('Promoted Patch Decisions (re-absorbed 2026-08-02)', 1355, 1540),
        ('Promoted Patch Decisions (re-absorbed 2026-08-02) > Persistence & Restore Architecture (promoted from patch restore_engine_2026_07_07 + successor lanes, 2026-07-07)', 1375, 1424),
        ('Promoted Patch Decisions (re-absorbed 2026-08-02) > Persistence Subsystem Topology (promoted from patch crystallizer_decomposition_2026_07_09, 2026-07-10)', 1425, 1467),
        ('Promoted Patch Decisions (re-absorbed 2026-08-02) > V3 Horizon Architecture (promoted 2026-07-12 from six patch dirs; owner-run full-tree green)', 1468, 1517),
        ('Promoted Patch Decisions (re-absorbed 2026-08-02) > Three-Lane Tail (promoted 2026-07-11; owner-directed finish of the public_cloud_seams, source_drift_preflight, and spell_index_graft lanes)', 1518, 1540),
        ('C1 Code Map (Core Only)', 1541, 2450),
        ('Diagrams', 2451, 2712),
        ('Diagrams > Creation Cache Compatibility', 2452, 2466),
        ('Diagrams > Named Scope Discovery and Replay', 2467, 2485),
        ('Diagrams > Pooled Hook Lifecycle', 2486, 2502),
        ('Diagrams > Bind Lifecycle', 2503, 2518),
        ('Diagrams > Scoped Purge', 2519, 2531),
        ('Diagrams > Registration Capability Foundation', 2532, 2550),
        ('Diagrams > Unresolved Input Resolution', 2551, 2570),
        ('Diagrams > Override Key-Set Plans', 2571, 2588),
        ('Diagrams > Conduit Lookup Coverage', 2589, 2605),
        ('Diagrams > ASCII Context Diagram (C4)', 2606, 2622),
        ('Diagrams > Mermaid Context Diagram (C4)', 2623, 2639),
        ('Diagrams > ASCII Conjure Pipeline Diagram', 2640, 2651),
        ('Diagrams > Mermaid Meld Flow', 2652, 2669),
        ('Diagrams > Mermaid Conduit Upgrade', 2670, 2689),
        ('Diagrams > Ordered Disposal Data Flow', 2690, 2712),
        ('Information Sources', 2713, 2834),
        ('Context / Handoff Summary', 2835, 3087),
        ('Context / Handoff Summary > Carried forward from the previous revision (2026-07-25)', 3052, 3087),
    ),
    'src_components.md': (
        ('Metadata', 3, 9),
        ('Scope', 10, 21),
        ('Indexing', 22, 107),
        ('Indexing > Verifying the `path:line` citations in this document', 63, 107),
        ('DO NOT ASSUME / Unknowns Gate', 108, 131),
        ('Unknowns', 132, 205),
        ('C3 Components Catalog', 206, 4764),
        ('C3 Components Catalog > Component: Public API and Runtime Guardrails', 208, 271),
        ('C3 Components Catalog > Component: Packaged Hardcopy Documents And Public Helper Exports', 272, 338),
        ('C3 Components Catalog > Component: Spellbook Core (Binding and Conjure)', 339, 603),
        ('C3 Components Catalog > Component: Binding Pipeline (Bind, Spell, SpellIndex)', 604, 789),
        ('C3 Components Catalog > Component: DI Descriptors and Contract Sockets', 790, 917),
        ('C3 Components Catalog > Component: Spellbook Configuration and System State', 918, 1034),
        ('C3 Components Catalog > Component: Aether Singleton (Global Runtime)', 1035, 1140),
        ('C3 Components Catalog > Component: AethericFrame Services', 1141, 1282),
        ('C3 Components Catalog > Component: Crystallizer Root, Persistence Record, And Module-World Surfaces', 1283, 1575),
        ('C3 Components Catalog > Component: AR Runtime Surface (Nexus, Rift, RiftSpace)', 1576, 2024),
        ('C3 Components Catalog > Component: Codegen Internal Engine', 2025, 2104),
        ('C3 Components Catalog > Component: Nexus Descriptor And ACL Managers', 2105, 2212),
        ('C3 Components Catalog > Component: RiftSpace Workstation And Command Surface', 2213, 2359),
        ('C3 Components Catalog > Component: Conduit Runtime (Normal and Lesser)', 2360, 2535),
        ('C3 Components Catalog > Component: ConduitWard and Contracts', 2536, 2695),
        ('C3 Components Catalog > Component: Creations and SpellSpace', 2696, 2887),
        ('C3 Components Catalog > Component: Meld Resolution Runtime', 2888, 3286),
        ('C3 Components Catalog > Component: SpellCompiler and Validation Pipeline', 3287, 3788),
        ('C3 Components Catalog > Component: DevOps Control Plane', 3789, 3886),
        ('C3 Components Catalog > Component: Transaction Admission Plane (Scope Acquisition)', 3887, 4068),
        ('C3 Components Catalog > Component: DevOps Information Strategies', 4069, 4177),
        ('C3 Components Catalog > Component: Aetheric Mediator Plane (WIRED - FRAME_CREATE LIVE)', 4178, 4459),
        ('C3 Components Catalog > Component: Logging and Initialization Helpers', 4460, 4564),
        ('C3 Components Catalog > Component: Spell Examination Profiles', 4565, 4690),
        ('C3 Components Catalog > Component: PhaseScheduler and UnitOfWork Orchestration', 4691, 4764),
        ('C2 Subcomponents Catalog', 4765, 6291),
        ('C2 Subcomponents Catalog > Subcomponent: Runtime Warning Guardrails', 4786, 4798),
        ('C2 Subcomponents Catalog > Subcomponent: Registration Refusal (Internal-Bind Manifest)', 4799, 4858),
        ('C2 Subcomponents Catalog > Subcomponent: Packaged Hardcopy Document Modules', 4859, 4877),
        ('C2 Subcomponents Catalog > Subcomponent: ProtocolCrafter Utility', 4878, 4897),
        ('C2 Subcomponents Catalog > Subcomponent: Aether Root Configuration Assembly', 4898, 4917),
        ('C2 Subcomponents Catalog > Subcomponent: Scan-Bind Module Scanner', 4918, 4932),
        ('C2 Subcomponents Catalog > Subcomponent: Spellbook Configuration Initialization', 4933, 4949),
        ('C2 Subcomponents Catalog > Subcomponent: Spellbook Conjure Pipeline', 4950, 4968),
        ('C2 Subcomponents Catalog > Subcomponent: Spellbook Binding Pipeline', 4969, 4985),
        ('C2 Subcomponents Catalog > Subcomponent: SpellIndex (Spell Index / Categorization)', 4986, 4999),
        ('C2 Subcomponents Catalog > Subcomponent: SpellIndex Mutation Surface', 5000, 5060),
        ('C2 Subcomponents Catalog > Subcomponent: Parameter DI Shape Classification', 5061, 5076),
        ('C2 Subcomponents Catalog > Subcomponent: SpellMap Descriptor', 5077, 5091),
        ('C2 Subcomponents Catalog > Subcomponent: SpellContract Descriptor', 5092, 5109),
        ('C2 Subcomponents Catalog > Subcomponent: SpellbookConfiguration Freeze and Validation', 5110, 5122),
        ('C2 Subcomponents Catalog > Subcomponent: PhaseScheduler Pipeline', 5123, 5135),
        ('C2 Subcomponents Catalog > Subcomponent: SpellCompiler Phase Artifacts', 5136, 5156),
        ('C2 Subcomponents Catalog > Subcomponent: Spell Validation Strategies', 5157, 5173),
        ('C2 Subcomponents Catalog > Subcomponent: System Validation (Phase 6)', 5174, 5186),
        ('C2 Subcomponents Catalog > Subcomponent: Change-Control Revalidation Wiring', 5187, 5204),
        ('C2 Subcomponents Catalog > Subcomponent: Aether Frame Registry', 5205, 5218),
        ('C2 Subcomponents Catalog > Subcomponent: Aether Conduit Lookups', 5219, 5243),
        ('C2 Subcomponents Catalog > Subcomponent: Conduit Normal Initialization', 5244, 5256),
        ('C2 Subcomponents Catalog > Subcomponent: Lesser Conduit Creation', 5257, 5269),
        ('C2 Subcomponents Catalog > Subcomponent: Conduit Upgrade to Normal', 5270, 5291),
        ('C2 Subcomponents Catalog > Subcomponent: Conduit Link and Sever', 5292, 5307),
        ('C2 Subcomponents Catalog > Subcomponent: Conduit Hook Wiring', 5308, 5330),
        ('C2 Subcomponents Catalog > Subcomponent: ConduitWard Contract Graph', 5331, 5343),
        ('C2 Subcomponents Catalog > Subcomponent: ConduitWard Conversion', 5344, 5358),
        ('C2 Subcomponents Catalog > Subcomponent: Ownership Transfer', 5359, 5376),
        ('C2 Subcomponents Catalog > Subcomponent: ConduitCluster Auto-Sharing', 5377, 5397),
        ('C2 Subcomponents Catalog > Subcomponent: ConduitCloud Registry', 5398, 5416),
        ('C2 Subcomponents Catalog > Subcomponent: Crystallizer Root', 5417, 5433),
        ('C2 Subcomponents Catalog > Subcomponent: SpellCrystal Manifest', 5434, 5454),
        ('C2 Subcomponents Catalog > Subcomponent: SyntheticModule Runtime', 5455, 5474),
        ('C2 Subcomponents Catalog > Subcomponent: MutationResearch Root (ResearchSet Registry)', 5475, 5563),
        ('C2 Subcomponents Catalog > Subcomponent: MutationResearch ResearchSet Package', 5564, 5736),
        ('C2 Subcomponents Catalog > Subcomponent: MutationResearch Configuration', 5737, 5750),
        ('C2 Subcomponents Catalog > Subcomponent: MutationResearch Configuration Builder', 5751, 5765),
        ('C2 Subcomponents Catalog > Subcomponent: Meld Execution Flow', 5766, 5782),
        ('C2 Subcomponents Catalog > Subcomponent: Meld Runtime Gating', 5783, 5796),
        ('C2 Subcomponents Catalog > Subcomponent: Creations Disposal Pipeline', 5797, 5810),
        ('C2 Subcomponents Catalog > Subcomponent: LesserCreations Transfer', 5811, 5826),
        ('C2 Subcomponents Catalog > Subcomponent: SpellSpace Scope Gate', 5827, 5839),
        ('C2 Subcomponents Catalog > Subcomponent: SpellSpace Thread State', 5840, 5881),
        ('C2 Subcomponents Catalog > Subcomponent: SpellSystemStates Registry', 5882, 5906),
        ('C2 Subcomponents Catalog > Subcomponent: Conduit Resolution State', 5907, 5921),
        ('C2 Subcomponents Catalog > Subcomponent: ChangeControl Dirty Roots', 5922, 5936),
        ('C2 Subcomponents Catalog > Subcomponent: Change-Control Revalidation', 5937, 5955),
        ('C2 Subcomponents Catalog > Subcomponent: Transaction Strategy Registry', 5956, 5973),
        ('C2 Subcomponents Catalog > Subcomponent: Transaction Strategy Families', 5974, 6003),
        ('C2 Subcomponents Catalog > Subcomponent: SafeLogger Adapter', 6004, 6016),
        ('C2 Subcomponents Catalog > Subcomponent: AetherUtilitySystem Provider Host', 6017, 6030),
        ('C2 Subcomponents Catalog > Subcomponent: Nexus Frame Registry and Access Policy', 6031, 6066),
        ('C2 Subcomponents Catalog > Subcomponent: NexusFrameBuilder Authored Frame Surface', 6067, 6090),
        ('C2 Subcomponents Catalog > Subcomponent: Frame Descriptor Publication Manager', 6091, 6106),
        ('C2 Subcomponents Catalog > Subcomponent: Frame ACL Manager', 6107, 6121),
        ('C2 Subcomponents Catalog > Subcomponent: Frame ACL Builder Surface', 6122, 6148),
        ('C2 Subcomponents Catalog > Subcomponent: Rift Single Space And Event Seam', 6149, 6175),
        ('C2 Subcomponents Catalog > Subcomponent: RiftSpace Workstation', 6176, 6189),
        ('C2 Subcomponents Catalog > Subcomponent: Rift-Backed Frame Viewer Surface', 6190, 6222),
        ('C2 Subcomponents Catalog > Subcomponent: RiftSpace Command System', 6223, 6250),
        ('C2 Subcomponents Catalog > Subcomponent: CodegenSystem Internal Engine', 6251, 6274),
        ('C2 Subcomponents Catalog > Subcomponent: SpellExaminer Profile Registry', 6275, 6291),
        ('Method-Level Call Flows (C1)', 6292, 6649),
        ('Method-Level Call Flows (C1) > Flow: Release Change to Cold Creation Cache', 6293, 6301),
        ('Method-Level Call Flows (C1) > Flow: Named Lesser Discovery and Structural Replay', 6302, 6313),
        ('Method-Level Call Flows (C1) > Flow: Aether Conduit Lookup by Name or Id', 6314, 6327),
        ("Method-Level Call Flows (C1) > Flow: Purge a Target's Retained Creations", 6328, 6338),
        ('Method-Level Call Flows (C1) > Flow: Import -> Runtime Guardrails', 6339, 6346),
        ('Method-Level Call Flows (C1) > Flow: Spellbook Init -> SpellbookConfiguration and Logging', 6347, 6354),
        ('Method-Level Call Flows (C1) > Flow: Aether Boot -> Utility Host, Crystallizer, and Nexus', 6355, 6365),
        ('Method-Level Call Flows (C1) > Flow: Nexus.create_rift -> Frame Policy -> Rift Registration', 6366, 6378),
        ('Method-Level Call Flows (C1) > Flow: Codegen Room Init -> Attach Internal Engine', 6379, 6385),
        ('Method-Level Call Flows (C1) > Flow: Frame ACL Family Revision -> Viewer Refresh', 6386, 6415),
        ('Method-Level Call Flows (C1) > Flow: FrameDescriptorManager Passive Publication', 6416, 6435),
        ('Method-Level Call Flows (C1) > Flow: RiftSpace Workstation Bind -> Target -> Call', 6436, 6444),
        ('Method-Level Call Flows (C1) > Flow: RiftSpace Command Surface -> Runtime Operation', 6445, 6455),
        ('Method-Level Call Flows (C1) > Flow: Codegen Command -> Engine Delegation -> Memory Emission', 6456, 6467),
        ('Method-Level Call Flows (C1) > Flow: Bind Spell -> SpellIndex and SpellSystemStates', 6468, 6481),
        ('Method-Level Call Flows (C1) > Flow: Conjure -> Phases -> Conduit', 6482, 6508),
        ('Method-Level Call Flows (C1) > Flow: Conduit.meld -> Meld -> CreationContext -> Creations', 6509, 6520),
        ('Method-Level Call Flows (C1) > Flow: Override Meld -> Key-Set Plan', 6521, 6533),
        ('Method-Level Call Flows (C1) > Flow: Conduit.has_live_creation -> Meld Probe', 6534, 6543),
        ('Method-Level Call Flows (C1) > Flow: SpellMap Default Resolution (Phase 3)', 6544, 6552),
        ('Method-Level Call Flows (C1) > Flow: Collection DI (list[FrameType])', 6553, 6558),
        ('Method-Level Call Flows (C1) > Flow: Unresolved Input (Phase 3 -> Meld)', 6559, 6573),
        ('Method-Level Call Flows (C1) > Flow: Meld-Time Validation Gate', 6574, 6580),
        ('Method-Level Call Flows (C1) > Flow: Create Lesser Conduit', 6581, 6587),
        ('Method-Level Call Flows (C1) > Flow: Upgrade Lesser Conduit -> Normal', 6588, 6600),
        ('Method-Level Call Flows (C1) > Flow: Link Conduits (Dynamic)', 6601, 6607),
        ('Method-Level Call Flows (C1) > Flow: Sever Conduit Link (Dynamic)', 6608, 6613),
        ('Method-Level Call Flows (C1) > Flow: Change-Control Revalidation', 6614, 6624),
        ('Method-Level Call Flows (C1) > Flow: Transfer Spell Ownership (Dynamic)', 6625, 6633),
        ('Method-Level Call Flows (C1) > Flow: SpellSpace Scoped Meld', 6634, 6639),
        ('Method-Level Call Flows (C1) > Flow: SpellExaminer.create_profile -> General/Detailed Profile', 6640, 6649),
        ('C1 Code Map (Core)', 6650, 8808),
        ('C1 Code Map (Core) > Full Package Inventory (exhaustive, retained)', 7747, 8808),
        ('Promoted Patch Detail (re-absorbed 2026-08-02)', 8809, 9261),
        ('Promoted Patch Detail (re-absorbed 2026-08-02) > Crystallizer Persistence & Restore (promoted from patch restore_engine_2026_07_07 + successor lanes, 2026-07-07)', 8822, 8932),
        ('Promoted Patch Detail (re-absorbed 2026-08-02) > Subsystem Decomposition (promoted from patch crystallizer_decomposition_2026_07_09, 2026-07-10)', 8933, 9014),
        ('Promoted Patch Detail (re-absorbed 2026-08-02) > V3 Horizon Iteration (promoted 2026-07-12 from six patch dirs: aether_lazy_frames_and_load_gate_2026_07_11, crystallizer_v3_horizon_2026_07_11, crystallizer_s2_user_source_ retention_2026_07_11, crystallizer_s3_impact_engine_2026_07_11, crystallizer_external_mesh_2026_07_12, mr_restore_build_stage_2026_07_11)', 9015, 9191),
        ('Promoted Patch Detail (re-absorbed 2026-08-02) > Three-Lane Tail (promoted 2026-07-11 from patch dirs public_cloud_seams_2026_07_12, source_drift_preflight_2026_07_12, spell_index_graft_2026_07_12; owner-directed finish)', 9192, 9261),
        ('Diagrams', 9262, 9417),
        ('Diagrams > Direct Resolution Admission', 9263, 9281),
        ('Diagrams > Required-Input Compiler Flow', 9282, 9304),
        ('Diagrams > Unresolved Input Flow', 9305, 9327),
        ('Diagrams > Override Key-Set Plan Flow', 9328, 9348),
        ('Diagrams > Mermaid: Conduit Upgrade', 9349, 9367),
        ('Diagrams > Mermaid: Conjure Pipeline', 9368, 9383),
        ('Diagrams > Mermaid: Meld Runtime', 9384, 9401),
        ('Diagrams > Mermaid: Ownership Transfer', 9402, 9417),
        ('Information Sources', 9418, 9621),
        ('Context / Handoff Summary', 9622, 9913),
    ),
    'src_graph.md': (
        ('src/melder/__architecture__.py', 11, 38),
        ('src/melder/__author__.py', 40, 59),
        ('src/melder/__components__.py', 61, 88),
        ('src/melder/__description__.py', 90, 109),
        ('src/melder/__graph_details__.py', 111, 138),
        ('src/melder/__graph_network__.py', 140, 167),
        ('src/melder/__init__.py', 169, 184),
        ('src/melder/__license__.py', 186, 205),
        ('src/melder/__melder_cache__/__melder_cache__.py', 207, 225),
        ('src/melder/__version__.py', 227, 246),
        ('src/melder/_build_assets/_agent_documentation/_builder.py', 248, 285),
        ('src/melder/_build_assets/_agent_documentation/agent_documentation.py', 287, 314),
        ('src/melder/_build_assets/_agent_documentation/manifest/agent_documentation_manifest.py', 316, 334),
        ('src/melder/_build_assets/_bind_guard/_builder.py', 336, 364),
        ('src/melder/_build_assets/_bind_guard/bind_guard.py', 366, 393),
        ('src/melder/_build_assets/_bind_guard/manifest/bind_guard_manifest.py', 395, 413),
        ('src/melder/_build_assets/_build_asset_runner.py', 415, 440),
        ('src/melder/_build_assets/_system_documents/_builder.py', 442, 471),
        ('src/melder/_build_assets/_system_documents/manifest/graph_adjacency_manifest.py', 473, 488),
        ('src/melder/_build_assets/_system_documents/manifest/system_documents_index.py', 490, 505),
        ('src/melder/_build_assets/_system_documents/manifest/system_documents_manifest.py', 507, 525),
        ('src/melder/_build_assets/_system_documents/payloads/src_architecture_payload.py', 527, 542),
        ('src/melder/_build_assets/_system_documents/payloads/src_components_payload.py', 544, 559),
        ('src/melder/_build_assets/_system_documents/payloads/src_graph_payload.py', 561, 576),
        ('src/melder/_build_assets/_system_documents/system_documents.py', 578, 603),
        ('src/melder/aether/aether.py', 605, 685),
        ('src/melder/aether/aether_configuration.py', 687, 742),
        ('src/melder/aether/aether_configuration_builder.py', 744, 797),
        ('src/melder/aether/aether_utility_system.py', 799, 848),
        ('src/melder/aether/aetheric_frame/aetheric_frame.py', 850, 920),
        ('src/melder/aether/aetheric_frame/aetheric_frame_configuration.py', 922, 972),
        ('src/melder/aether/aetheric_frame/conduit_cloud.py', 974, 1023),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/change_control_manager.py', 1025, 1084),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/conflict_manager/conflict_manager.py', 1086, 1127),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/embargo_manager/embargo_manager.py', 1129, 1208),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/orchestrator/orchestrator.py', 1210, 1262),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/orchestrator/staged_mutation.py', 1264, 1305),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/add_spell_or_index_to_contract_transaction_strategy.py', 1307, 1341),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/add_to_index_transaction_strategy.py', 1343, 1377),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/bind_transaction_strategy.py', 1379, 1426),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/cluster_join_transaction_strategy.py', 1428, 1468),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/cluster_leave_transaction_strategy.py', 1470, 1510),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/cluster_link_transaction_strategy.py', 1512, 1560),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/conjure_transaction_strategy.py', 1562, 1596),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/elect_conduit_cluster_leader_transaction_strategy.py', 1598, 1632),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/link_transaction_strategy.py', 1634, 1682),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/notch_transaction_strategy.py', 1684, 1718),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/remove_from_index_transaction_strategy.py', 1720, 1754),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/remove_spell_or_index_from_contract_transaction_strategy.py', 1756, 1790),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/transaction_strategy.py', 1792, 1820),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/transaction_strategy_builder.py', 1822, 1870),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/transfer_ownership_transaction_strategy.py', 1872, 1921),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/unelect_conduit_cluster_leader_transaction_strategy.py', 1923, 1957),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/strategies/unlink_transaction_strategy.py', 1959, 2009),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/transaction_manager.py', 2011, 2058),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/transaction_mediator.py', 2060, 2128),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_manager/transaction_session.py', 2130, 2182),
        ('src/melder/aether/aetheric_frame/dev_ops/change_control_manager/transaction_request/transaction_request.py', 2184, 2231),
        ('src/melder/aether/aetheric_frame/dev_ops/conduit_lineage_gate_ops.py', 2233, 2275),
        ('src/melder/aether/aetheric_frame/dev_ops/dev_ops_manager.py', 2277, 2336),
        ('src/melder/aether/aetheric_frame/dev_ops/devops_identity.py', 2338, 2385),
        ('src/melder/aether/aetheric_frame/dev_ops/devops_information_registry.py', 2387, 2449),
        ('src/melder/aether/aetheric_frame/dev_ops/devops_information_strategy.py', 2451, 2479),
        ('src/melder/aether/aetheric_frame/dev_ops/devops_information_strategy_builder.py', 2481, 2538),
        ('src/melder/aether/aetheric_frame/dev_ops/incident_manager/incident.py', 2540, 2586),
        ('src/melder/aether/aetheric_frame/dev_ops/incident_manager/incident_manager.py', 2588, 2634),
        ('src/melder/aether/aetheric_frame/dev_ops/incident_manager/incident_severity.py', 2636, 2662),
        ('src/melder/aether/aetheric_frame/dev_ops/incident_manager/incident_status.py', 2664, 2690),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/cluster_fanout_strategy.py', 2692, 2737),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/frame_operational_view_strategy.py', 2739, 2778),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/information_strategy_support.py', 2780, 2822),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/registry_consistency_audit_strategy.py', 2824, 2861),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/transaction_activity_view_strategy.py', 2863, 2908),
        ('src/melder/aether/aetheric_frame/dev_ops/information_strategies/transfer_blast_radius_strategy.py', 2910, 2955),
        ('src/melder/aether/aetheric_frame/dev_ops/risk_manager/risk_manager.py', 2957, 3014),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/conduit_resolution_state.py', 3016, 3063),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/spell_state.py', 3065, 3091),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/spell_state_change_reason.py', 3093, 3119),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/spell_system_state.py', 3121, 3169),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/spell_system_states.py', 3171, 3230),
        ('src/melder/aether/aetheric_frame/dev_ops/spell_system_states/spell_validity.py', 3232, 3258),
        ('src/melder/aether/aetheric_frame/lookup_container.py', 3260, 3296),
        ('src/melder/aether/aetheric_mediator/admission_orchestrator.py', 3298, 3340),
        ('src/melder/aether/aetheric_mediator/admission_result.py', 3342, 3395),
        ('src/melder/aether/aetheric_mediator/claim_mode.py', 3397, 3442),
        ('src/melder/aether/aetheric_mediator/claim_table.py', 3444, 3519),
        ('src/melder/aether/aetheric_mediator/identity.py', 3521, 3562),
        ('src/melder/aether/aetheric_mediator/information_registry.py', 3564, 3624),
        ('src/melder/aether/aetheric_mediator/mediator.py', 3626, 3675),
        ('src/melder/aether/aetheric_mediator/participation.py', 3677, 3720),
        ('src/melder/aether/aetheric_mediator/scope_keys.py', 3722, 3766),
        ('src/melder/aether/aetheric_mediator/staged_transaction.py', 3768, 3809),
        ('src/melder/aether/aetheric_mediator/strategies/agent_repair_transaction_strategy.py', 3811, 3847),
        ('src/melder/aether/aetheric_mediator/strategies/checkpoint_load_transaction_strategy.py', 3849, 3884),
        ('src/melder/aether/aetheric_mediator/strategies/formation_load_transaction_strategy.py', 3886, 3921),
        ('src/melder/aether/aetheric_mediator/strategies/frame_create_transaction_strategy.py', 3923, 3959),
        ('src/melder/aether/aetheric_mediator/strategies/index_graft_transaction_strategy.py', 3961, 3997),
        ('src/melder/aether/aetheric_mediator/strategies/subsystem_activate_transaction_strategy.py', 3999, 4035),
        ('src/melder/aether/aetheric_mediator/strategies/subsystem_configure_transaction_strategy.py', 4037, 4074),
        ('src/melder/aether/aetheric_mediator/strategies/subsystem_deactivate_transaction_strategy.py', 4076, 4112),
        ('src/melder/aether/aetheric_mediator/strategy_builder.py', 4114, 4159),
        ('src/melder/aether/aetheric_mediator/transaction_request.py', 4161, 4220),
        ('src/melder/aether/aetheric_mediator/transaction_session.py', 4222, 4307),
        ('src/melder/aether/aetheric_mediator/transaction_strategy.py', 4309, 4340),
        ('src/melder/aether/aetheric_mediator/transaction_type.py', 4342, 4369),
        ('src/melder/aether/aetheric_mediator/unwind_conflict_error.py', 4371, 4400),
        ('src/melder/aether/conduit/conduit.py', 4402, 4503),
        ('src/melder/aether/conduit/conduit_cluster.py', 4505, 4559),
        ('src/melder/aether/conduit/conduit_pool.py', 4561, 4604),
        ('src/melder/aether/conduit/conduit_state/conduit_state.py', 4606, 4642),
        ('src/melder/aether/conduit/conduit_ward/conduit_ward.py', 4644, 4713),
        ('src/melder/aether/conduit/conduit_ward/contract/contract.py', 4715, 4771),
        ('src/melder/aether/conduit/conduit_ward/contract/contract_types/contract_types.py', 4773, 4802),
        ('src/melder/aether/conduit/conduit_ward/contract/detail_reason.py', 4804, 4833),
        ('src/melder/aether/conduit/conduit_ward/contract/details.py', 4835, 4900),
        ('src/melder/aether/conduit/conduit_ward/permissions/permissions.py', 4902, 4931),
        ('src/melder/aether/conduit/conduit_ward/policies/policies.py', 4933, 4962),
        ('src/melder/aether/conduit/conduit_ward/transfer/transfer_of_ownership.py', 4964, 5023),
        ('src/melder/aether/conduit/creations/cluster_creations.py', 5025, 5067),
        ('src/melder/aether/conduit/creations/conduit_creations.py', 5069, 5110),
        ('src/melder/aether/conduit/creations/creations.py', 5112, 5165),
        ('src/melder/aether/conduit/meld/conduit_meld.py', 5167, 5222),
        ('src/melder/aether/conduit/meld/contracts/spell_contract.py', 5224, 5267),
        ('src/melder/aether/conduit/meld/contracts/spell_map.py', 5269, 5313),
        ('src/melder/aether/conduit/meld/creation_context/creation_context.py', 5315, 5361),
        ('src/melder/aether/conduit/meld/creation_context/creation_context_builder.py', 5363, 5401),
        ('src/melder/aether/conduit/meld/creation_context/creation_context_factory.py', 5403, 5453),
        ('src/melder/aether/conduit/meld/creation_context/creation_context_rebuild.py', 5455, 5500),
        ('src/melder/aether/conduit/meld/meld.py', 5502, 5584),
        ('src/melder/aether/conduit/meld/spellspace_meld.py', 5586, 5645),
        ('src/melder/aether/conduit/spell_space/spell_space.py', 5647, 5703),
        ('src/melder/aether/conduit/spell_space/spell_space_pool.py', 5705, 5761),
        ('src/melder/aether/conduit/spell_space/spell_space_thread_state.py', 5763, 5822),
        ('src/melder/aether/spellbook/bind/bind.py', 5824, 5896),
        ('src/melder/aether/spellbook/bind/scan.py', 5898, 5955),
        ('src/melder/aether/spellbook/bind/spell_index.py', 5957, 6006),
        ('src/melder/aether/spellbook/configuration/spellbook_configuration.py', 6008, 6058),
        ('src/melder/aether/spellbook/configuration/system_state.py', 6060, 6086),
        ('src/melder/aether/spellbook/existence/existence.py', 6088, 6114),
        ('src/melder/aether/spellbook/resolution_style_matrix.py', 6116, 6153),
        ('src/melder/aether/spellbook/spell.py', 6155, 6237),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_injection_analysis.py', 6239, 6309),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_occurrence_contract_analysis.py', 6311, 6349),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_occurrence_instance_analysis.py', 6351, 6389),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_occurrence_order_analysis.py', 6391, 6429),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_runtime_analysis.py', 6431, 6482),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/data/spell_site_graph_analysis.py', 6484, 6559),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/spell_artifact_processor.py', 6561, 6613),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/spell_artifact_processor_strategy.py', 6615, 6653),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/spell_artifact_processor_strategy_builder.py', 6655, 6719),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/spell_codegen_model.py', 6721, 6771),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_existence_occurrence_processor_strategy.py', 6773, 6816),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_injection_processor_strategy.py', 6818, 6871),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_occurrence_contract_processor_strategy.py', 6873, 6923),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_occurrence_instance_processor_strategy.py', 6925, 6973),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_occurrence_order_processor_strategy.py', 6975, 7023),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_runtime_processor_strategy.py', 7025, 7074),
        ('src/melder/aether/spellbook/spell_compiler/artifact_processor/strategies/spell_site_graph_processor_strategy.py', 7076, 7126),
        ('src/melder/aether/spellbook/spell_compiler/blueprints/root_resolution_blueprint.py', 7128, 7175),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation/spell_codegen_creation.py', 7177, 7215),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/codegen_creation_discovery.py', 7217, 7243),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/codegen_creation_discovery_strategy.py', 7245, 7273),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/codegen_creation_discovery_strategy_builder.py', 7275, 7329),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/codegen_creation_discovery_system.py', 7331, 7379),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/strategies/generalized_cache_codegen_creation_discovery_strategy.py', 7381, 7433),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/strategies/generalized_codegen_creation_discovery_strategy.py', 7435, 7487),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/strategies/many_only_codegen_creation_discovery_strategy.py', 7489, 7540),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_discovery_system/strategies/solo_codegen_creation_discovery_strategy.py', 7542, 7593),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/codegen_creation_system.py', 7595, 7652),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/codegen_creation_family_step.py', 7654, 7682),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/codegen_creation_schema_helpers.py', 7684, 7727),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/creation_runtime_door_compiler.py', 7729, 7761),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/manifest_creation_cache.py', 7763, 7796),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/override_key_resolver.py', 7798, 7858),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/site_plan_lowering.py', 7860, 7965),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/shared_assets/site_plan_override_runtime.py', 7967, 8027),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/spell_codegen_strategy.py', 8029, 8067),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/spell_codegen_strategy_builder.py', 8069, 8120),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/compilers/generalized_cache_runtime_rows_SCRATCH.py', 8122, 8140),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/compilers/generalized_manifest_no_overrides_compiler.py', 8142, 8175),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/compilers/generalized_no_overrides_codegen_creation_compiler.py', 8177, 8207),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/compilers/generalized_runtime_library.py', 8209, 8238),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/compilers/generalized_runtime_rows.py', 8240, 8278),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/generalized_codegen_creation_strategy.py', 8280, 8328),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/generalized_creation_cache.py', 8330, 8369),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/generalized_manifest_state.py', 8371, 8408),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/hydration/generalized_binding_resolver.py', 8410, 8470),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/hydration/generalized_hydrator.py', 8472, 8534),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/manifest/generalized_manifest.py', 8536, 8570),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/steps/generalized_lazy_door_step.py', 8572, 8622),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/generalized/steps/generalized_manifest_step.py', 8624, 8665),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/compilers/many_only_no_overrides_codegen_creation_compiler.py', 8667, 8704),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/hydration/many_only_hydrator.py', 8706, 8761),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/manifest/many_only_manifest.py', 8763, 8797),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/many_only_codegen_creation_helpers.py', 8799, 8826),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/many_only_codegen_creation_state.py', 8828, 8865),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/many_only_codegen_creation_strategy.py', 8867, 8921),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/many_only_creation_cache.py', 8923, 8955),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/steps/many_only_lazy_door_step.py', 8957, 9004),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/many_only/steps/many_only_manifest_step.py', 9006, 9053),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/compilers/solo_no_overrides_codegen_creation_compiler.py', 9055, 9084),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/compilers/solo_overrides_codegen_creation_compiler.py', 9086, 9115),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/hydration/solo_hydrator.py', 9117, 9172),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/manifest/solo_manifest.py', 9174, 9203),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/solo_codegen_creation_state.py', 9205, 9242),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/solo_codegen_creation_strategy.py', 9244, 9296),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/solo_creation_cache.py', 9298, 9330),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/steps/solo_creation_context_setup_step.py', 9332, 9371),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/steps/solo_lazy_door_step.py', 9373, 9420),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/steps/solo_manifest_step.py', 9422, 9463),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/steps/solo_no_overrides_codegen_creation_step.py', 9465, 9506),
        ('src/melder/aether/spellbook/spell_compiler/codegen_creation_system/strategies/solo/steps/solo_overrides_codegen_creation_step.py', 9508, 9549),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/codegen_plan_discovery.py', 9551, 9578),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/codegen_plan_discovery_strategy.py', 9580, 9618),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/codegen_plan_discovery_strategy_builder.py', 9620, 9675),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/codegen_plan_discovery_system.py', 9677, 9726),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/strategies/generalized_codegen_plan_discovery_strategy.py', 9728, 9771),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/strategies/many_only_codegen_plan_discovery_strategy.py', 9773, 9818),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/codegen_plan_discovery_system/strategies/solo_codegen_plan_discovery_strategy.py', 9820, 9863),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/data/many_only_codegen_plan.py', 9865, 9997),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/data/spell_generalized_codegen_lane_plan.py', 9999, 10155),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/spell_codegen_plan.py', 10157, 10195),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/spell_codegen_plan_strategy.py', 10197, 10235),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/spell_codegen_plan_strategy_builder.py', 10237, 10292),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/spell_codegen_planner.py', 10294, 10351),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/strategies/spell_generalized_codegen_plan_strategy.py', 10353, 10398),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/strategies/spell_generalized_solo_codegen_plan_strategy.py', 10400, 10445),
        ('src/melder/aether/spellbook/spell_compiler/codegen_planner/strategies/spell_many_only_codegen_plan_strategy.py', 10447, 10492),
        ('src/melder/aether/spellbook/spell_compiler/dag/dag_index.py', 10494, 10546),
        ('src/melder/aether/spellbook/spell_compiler/dag/dag_node.py', 10548, 10591),
        ('src/melder/aether/spellbook/spell_compiler/dag/directed_acyclic_work_graph.py', 10593, 10639),
        ('src/melder/aether/spellbook/spell_compiler/dag/resolution_frame/resolution_frame.py', 10641, 10683),
        ('src/melder/aether/spellbook/spell_compiler/dag/socket_kind.py', 10685, 10712),
        ('src/melder/aether/spellbook/spell_compiler/dag/target_spec.py', 10714, 10767),
        ('src/melder/aether/spellbook/spell_compiler/executor_code_cache.py', 10769, 10790),
        ('src/melder/aether/spellbook/spell_compiler/executor_factory_cache.py', 10792, 10813),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_1.py', 10815, 10860),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_10.py', 10862, 10912),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_11.py', 10914, 10964),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_2.py', 10966, 11013),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_3.py', 11015, 11078),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_4.py', 11080, 11125),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_5.py', 11127, 11188),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_6.py', 11190, 11256),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_7.py', 11258, 11303),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_8.py', 11305, 11354),
        ('src/melder/aether/spellbook/spell_compiler/phases/compiler_phase_9.py', 11356, 11405),
        ('src/melder/aether/spellbook/spell_compiler/phases/shared_compiler_executions.py', 11407, 11444),
        ('src/melder/aether/spellbook/spell_compiler/phases/utility.py', 11446, 11472),
        ('src/melder/aether/spellbook/spell_compiler/profiles/resolution_profile.py', 11474, 11589),
        ('src/melder/aether/spellbook/spell_compiler/shared_assets/codegen_signature.py', 11591, 11619),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/data/spell_existence_occurrence_analysis.py', 11621, 11666),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/data/spell_occurrence_graph_analysis.py', 11668, 11708),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/spell_analyzer.py', 11710, 11758),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/spell_analyzer_strategy.py', 11760, 11796),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/spell_analyzer_strategy_builder.py', 11798, 11847),
        ('src/melder/aether/spellbook/spell_compiler/spell_analyzer/strategies/spell_occurrence_graph_analyzer_strategy.py', 11849, 11907),
        ('src/melder/aether/spellbook/spell_compiler/spell_compiler.py', 11909, 11992),
        ('src/melder/aether/spellbook/spell_compiler/spell_compiler_artifact.py', 11994, 12055),
        ('src/melder/aether/spellbook/spell_compiler/spell_compiler_system.py', 12057, 12106),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/inspectors/class_inspector.py', 12108, 12154),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/inspectors/inspector_utility.py', 12156, 12182),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/inspectors/method_inspector.py', 12184, 12230),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/inspectors/profiles/class_profile.py', 12232, 12265),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/inspectors/profiles/method_profile.py', 12267, 12300),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/profiles/binding_profile.py', 12302, 12418),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/profiles/detailed_profile.py', 12420, 12470),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/profiles/general_profile.py', 12472, 12518),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/spell_examiner.py', 12520, 12566),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/strategies/binding_profile_strategy.py', 12568, 12617),
        ('src/melder/aether/spellbook/spell_compiler/spell_examiner/strategies/resolution_profile_strategy.py', 12619, 12659),
        ('src/melder/aether/spellbook/spell_compiler/spell_requirements_finder/parameter_di_shape.py', 12661, 12687),
        ('src/melder/aether/spellbook/spell_compiler/spell_requirements_finder/spell_parameter_requirements.py', 12689, 12734),
        ('src/melder/aether/spellbook/spell_compiler/spell_requirements_finder/spell_requirements.py', 12736, 12779),
        ('src/melder/aether/spellbook/spell_compiler/spell_requirements_finder/spell_requirements_finder.py', 12781, 12832),
        ('src/melder/aether/spellbook/spell_compiler/structural_snapshot/structural_snapshot.py', 12834, 12865),
        ('src/melder/aether/spellbook/spell_compiler/symbolic_graph/spell_symbolic_dependency.py', 12867, 12907),
        ('src/melder/aether/spellbook/spell_compiler/symbolic_graph/spell_symbolic_graph.py', 12909, 12955),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_adjacency_builder.py', 12957, 13001),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_adjacency_snapshot.py', 13003, 13043),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_index.py', 13045, 13090),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_node.py', 13092, 13133),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_root_blueprint_builder.py', 13135, 13179),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_validation_state.py', 13181, 13220),
        ('src/melder/aether/spellbook/spell_compiler/system/spell_system_validation_system.py', 13222, 13276),
        ('src/melder/aether/spellbook/spell_compiler/system/system_diagnostic.py', 13278, 13329),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/broken_spell_in_dag_strategy.py', 13331, 13373),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/contract_graph_cycle_strategy.py', 13375, 13417),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/contracted_version_drift_strategy.py', 13419, 13461),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/cycle_detection_strategy.py', 13463, 13507),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/dependency_type_sanity_strategy.py', 13509, 13551),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/empty_collection_strategy.py', 13553, 13593),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/graph_consistency_strategy.py', 13595, 13637),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/identity_mixing_strategy.py', 13639, 13681),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/index_coverage_strategy.py', 13683, 13725),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/index_dependency_sanity_strategy.py', 13727, 13770),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/lineage_alignment_strategy.py', 13772, 13814),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/lineage_version_conflict_strategy.py', 13816, 13857),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/missing_phase4_strategy.py', 13859, 13901),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/ownership_consistency_strategy.py', 13903, 13944),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/root_coverage_strategy.py', 13946, 13988),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/root_lineage_conflict_strategy.py', 13990, 14031),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/root_reachability_strategy.py', 14033, 14075),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/root_scale_limit_strategy.py', 14077, 14120),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/root_viability_strategy.py', 14122, 14165),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/scope_ordering_strategy.py', 14167, 14210),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/strategy_base.py', 14212, 14243),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/topology_dependency_mismatch_strategy.py', 14245, 14287),
        ('src/melder/aether/spellbook/spell_compiler/system/validation/visibility_gap_strategy.py', 14289, 14331),
        ('src/melder/aether/spellbook/spell_compiler/topology/spell_local_topology.py', 14333, 14389),
        ('src/melder/aether/spellbook/spell_compiler/validation/spell_validation_context.py', 14391, 14433),
        ('src/melder/aether/spellbook/spell_compiler/validation/spell_validation_issue.py', 14435, 14474),
        ('src/melder/aether/spellbook/spell_compiler/validation/spell_validation_result.py', 14476, 14518),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/annotation_shape_guard_strategy.py', 14520, 14566),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/binding_resolution_cycle_strategy.py', 14568, 14614),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/callable_profile_hygiene_strategy.py', 14616, 14658),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/circular_dependency_strategy.py', 14660, 14705),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/contract_provider_presence_strategy.py', 14707, 14752),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/dangling_dependency_strategy.py', 14754, 14797),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/duplicate_spell_name_strategy.py', 14799, 14842),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/existing_creation_compatibility_strategy.py', 14844, 14886),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/parameter_policy_strategy.py', 14888, 14932),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/required_holes_strategy.py', 14934, 14980),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/resolution_frame_presence_strategy.py', 14982, 15024),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/self_validation_strategy.py', 15026, 15069),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/spell_validation_strategy.py', 15071, 15111),
        ('src/melder/aether/spellbook/spell_compiler/validation/strategies/spellmap_shape_validation_strategy.py', 15113, 15156),
        ('src/melder/aether/spellbook/spell_compiler/validation/validation_system.py', 15158, 15225),
        ('src/melder/aether/spellbook/spell_types/spell_types.py', 15227, 15253),
        ('src/melder/aether/spellbook/spellbinder.py', 15255, 15301),
        ('src/melder/aether/spellbook/spellbook.py', 15303, 15402),
        ('src/melder/aether/spellbook/spellbook_creation_system.py', 15404, 15473),
        ('src/melder/crystallizer/asset_management/adapters/sqlite_mesh_adapter.py', 15475, 15518),
        ('src/melder/crystallizer/asset_management/asset_management_system.py', 15520, 15581),
        ('src/melder/crystallizer/asset_management/crystallizer_cache.py', 15583, 15631),
        ('src/melder/crystallizer/asset_management/external_persistence_manager.py', 15633, 15684),
        ('src/melder/crystallizer/asset_management/external_persistence_manager_configuration.py', 15686, 15732),
        ('src/melder/crystallizer/asset_management/mesh_interface_contract.py', 15734, 15762),
        ('src/melder/crystallizer/configuration/crystallizer_configuration.py', 15764, 15813),
        ('src/melder/crystallizer/configuration/crystallizer_configuration_builder.py', 15815, 15864),
        ('src/melder/crystallizer/crystal_analysis/conduit_hierarchy.py', 15866, 15902),
        ('src/melder/crystallizer/crystal_analysis/crystal_analysis_result.py', 15904, 15950),
        ('src/melder/crystallizer/crystal_analysis/crystal_analyzer.py', 15952, 16023),
        ('src/melder/crystallizer/crystal_analysis/custody/binary_unknown_custody_strategy.py', 16025, 16059),
        ('src/melder/crystallizer/crystal_analysis/custody/site_package_custody_strategy.py', 16061, 16096),
        ('src/melder/crystallizer/crystal_analysis/custody/source_custody_strategy.py', 16098, 16133),
        ('src/melder/crystallizer/crystal_analysis/custody/synthetic_custody_strategy.py', 16135, 16169),
        ('src/melder/crystallizer/crystal_analysis/custody/user_source_custody_strategy.py', 16171, 16206),
        ('src/melder/crystallizer/crystal_analysis/impact_engine.py', 16208, 16249),
        ('src/melder/crystallizer/crystal_analysis/physical_source_cache.py', 16251, 16287),
        ('src/melder/crystallizer/crystal_analysis/preflight/cluster_membership_strategy.py', 16289, 16322),
        ('src/melder/crystallizer/crystal_analysis/preflight/conduit_hierarchy_strategy.py', 16324, 16362),
        ('src/melder/crystallizer/crystal_analysis/preflight/configuration_loss_strategy.py', 16364, 16397),
        ('src/melder/crystallizer/crystal_analysis/preflight/contract_peer_strategy.py', 16399, 16432),
        ('src/melder/crystallizer/crystal_analysis/preflight/frame_posture_strategy.py', 16434, 16467),
        ('src/melder/crystallizer/crystal_analysis/preflight/hydration_strategy.py', 16469, 16503),
        ('src/melder/crystallizer/crystal_analysis/preflight/link_integrity_strategy.py', 16505, 16538),
        ('src/melder/crystallizer/crystal_analysis/preflight/mutation_research_composition_strategy.py', 16540, 16574),
        ('src/melder/crystallizer/crystal_analysis/preflight/persistence_analysis_strategy.py', 16576, 16604),
        ('src/melder/crystallizer/crystal_analysis/preflight/persistence_analyzer.py', 16606, 16658),
        ('src/melder/crystallizer/crystal_analysis/preflight/source_drift_strategy.py', 16660, 16700),
        ('src/melder/crystallizer/crystal_analysis/preflight/synthetic_source_integrity_strategy.py', 16702, 16735),
        ('src/melder/crystallizer/crystal_analysis/preflight/user_source_integrity_strategy.py', 16737, 16771),
        ('src/melder/crystallizer/crystal_analysis/strategies/base_strategy.py', 16773, 16826),
        ('src/melder/crystallizer/crystal_analysis/strategies/dependency_view_strategy.py', 16828, 16865),
        ('src/melder/crystallizer/crystal_analysis/strategies/export_surface_strategy.py', 16867, 16904),
        ('src/melder/crystallizer/crystal_analysis/strategies/from_import_statement_strategy.py', 16906, 16943),
        ('src/melder/crystallizer/crystal_analysis/strategies/import_statement_strategy.py', 16945, 16982),
        ('src/melder/crystallizer/crystal_loader_system/bootstrap_loader.py', 16984, 17034),
        ('src/melder/crystallizer/crystal_loader_system/crystal_loader_system.py', 17036, 17091),
        ('src/melder/crystallizer/crystal_loader_system/graft_runner.py', 17093, 17152),
        ('src/melder/crystallizer/crystal_loader_system/load_admission.py', 17154, 17209),
        ('src/melder/crystallizer/crystal_loader_system/load_plan.py', 17211, 17254),
        ('src/melder/crystallizer/crystal_loader_system/restore_engine.py', 17256, 17348),
        ('src/melder/crystallizer/crystal_loader_system/user_world_rebuild.py', 17350, 17371),
        ('src/melder/crystallizer/crystallizer.py', 17373, 17451),
        ('src/melder/crystallizer/crystals/aether_crystal.py', 17453, 17490),
        ('src/melder/crystallizer/crystals/aetheric_frame_crystal.py', 17492, 17535),
        ('src/melder/crystallizer/crystals/cluster_crystal.py', 17537, 17575),
        ('src/melder/crystallizer/crystals/conduit_crystal.py', 17577, 17621),
        ('src/melder/crystallizer/crystals/contract_crystal.py', 17623, 17661),
        ('src/melder/crystallizer/crystals/crystallizer_crystal.py', 17663, 17700),
        ('src/melder/crystallizer/crystals/mutation_research_crystal.py', 17702, 17739),
        ('src/melder/crystallizer/crystals/nexus_crystal.py', 17741, 17777),
        ('src/melder/crystallizer/crystals/recorded_unit_state.py', 17779, 17807),
        ('src/melder/crystallizer/crystals/spell_crystal.py', 17809, 17866),
        ('src/melder/crystallizer/crystals/spell_index_crystal.py', 17868, 17905),
        ('src/melder/crystallizer/crystals/spellbook_crystal.py', 17907, 17950),
        ('src/melder/crystallizer/persistence/persistence_crystal.py', 17952, 18000),
        ('src/melder/crystallizer/persistence/persistence_profile.py', 18002, 18055),
        ('src/melder/crystallizer/persistence/persistence_system.py', 18057, 18117),
        ('src/melder/crystallizer/persistence/record_version.py', 18119, 18158),
        ('src/melder/crystallizer/synthetic_module.py', 18160, 18233),
        ('src/melder/mutation_research/diff/diff_engine.py', 18235, 18300),
        ('src/melder/mutation_research/diff/diff_strategy.py', 18302, 18347),
        ('src/melder/mutation_research/diff/strategies/part_diff_strategy.py', 18349, 18389),
        ('src/melder/mutation_research/diff/strategies/source_diff_strategy.py', 18391, 18430),
        ('src/melder/mutation_research/diff/strategies/structural_diff_strategy.py', 18432, 18471),
        ('src/melder/mutation_research/group_diff/group_diff_engine.py', 18473, 18524),
        ('src/melder/mutation_research/group_diff/group_diff_strategy.py', 18526, 18567),
        ('src/melder/mutation_research/group_diff/strategies/member_diff_strategy.py', 18569, 18608),
        ('src/melder/mutation_research/mutation_configuration.py', 18610, 18661),
        ('src/melder/mutation_research/mutation_configuration_builder.py', 18663, 18712),
        ('src/melder/mutation_research/mutation_research.py', 18714, 18803),
        ('src/melder/mutation_research/research_set/grouped_research_node.py', 18805, 18848),
        ('src/melder/mutation_research/research_set/network_versioner.py', 18850, 18899),
        ('src/melder/mutation_research/research_set/research_journal.py', 18901, 18952),
        ('src/melder/mutation_research/research_set/research_lane.py', 18954, 19031),
        ('src/melder/mutation_research/research_set/research_node.py', 19033, 19080),
        ('src/melder/mutation_research/research_set/research_set.py', 19082, 19154),
        ('src/melder/mutation_research/research_set/residence_registry.py', 19156, 19206),
        ('src/melder/mutation_research/research_set/transition_entry.py', 19208, 19266),
        ('src/melder/mutation_research/synthesis/structural_synthesizer.py', 19268, 19317),
        ('src/melder/nexus/acl/builder/frame_acl_builder.py', 19319, 19380),
        ('src/melder/nexus/acl/builder/frame_acl_codegen_builder.py', 19382, 19434),
        ('src/melder/nexus/acl/builder/frame_acl_command_builder.py', 19436, 19488),
        ('src/melder/nexus/acl/builder/frame_acl_view_builder.py', 19490, 19542),
        ('src/melder/nexus/acl/configurations/frame_acl_codegen_configuration.py', 19544, 19593),
        ('src/melder/nexus/acl/configurations/frame_acl_command_configuration.py', 19595, 19644),
        ('src/melder/nexus/acl/configurations/frame_acl_view_configuration.py', 19646, 19695),
        ('src/melder/nexus/acl/configurations/profiles/builder/frame_acl_profile_builder.py', 19697, 19772),
        ('src/melder/nexus/acl/configurations/profiles/codegen/frame_acl_codegen_profile.py', 19774, 19823),
        ('src/melder/nexus/acl/configurations/profiles/codegen/frame_acl_codegen_profile_builder.py', 19825, 19881),
        ('src/melder/nexus/acl/configurations/profiles/codegen/full_access_profile.py', 19883, 19920),
        ('src/melder/nexus/acl/configurations/profiles/codegen/hybrid_profile.py', 19922, 19967),
        ('src/melder/nexus/acl/configurations/profiles/codegen/permissive_profile.py', 19969, 20014),
        ('src/melder/nexus/acl/configurations/profiles/codegen/precision.py', 20016, 20062),
        ('src/melder/nexus/acl/configurations/profiles/codegen/safe_profile.py', 20064, 20110),
        ('src/melder/nexus/acl/configurations/profiles/codegen/stdlib_import_sets.py', 20112, 20133),
        ('src/melder/nexus/acl/configurations/profiles/command/frame_acl_command_profile.py', 20135, 20186),
        ('src/melder/nexus/acl/configurations/profiles/command/frame_acl_command_profile_builder.py', 20188, 20241),
        ('src/melder/nexus/acl/configurations/profiles/command/hybrid_profile.py', 20243, 20286),
        ('src/melder/nexus/acl/configurations/profiles/command/permissive_profile.py', 20288, 20331),
        ('src/melder/nexus/acl/configurations/profiles/command/precision.py', 20333, 20376),
        ('src/melder/nexus/acl/configurations/profiles/command/safe_profile.py', 20378, 20421),
        ('src/melder/nexus/acl/configurations/profiles/frame_acl_profile.py', 20423, 20474),
        ('src/melder/nexus/acl/configurations/profiles/rules/frame_acl_rule.py', 20476, 20517),
        ('src/melder/nexus/acl/configurations/profiles/rules/frame_acl_ruleset.py', 20519, 20565),
        ('src/melder/nexus/acl/configurations/profiles/view/frame_acl_view_profile.py', 20567, 20618),
        ('src/melder/nexus/acl/configurations/profiles/view/frame_acl_view_profile_builder.py', 20620, 20673),
        ('src/melder/nexus/acl/configurations/profiles/view/hybrid_profile.py', 20675, 20718),
        ('src/melder/nexus/acl/configurations/profiles/view/permissive_profile.py', 20720, 20763),
        ('src/melder/nexus/acl/configurations/profiles/view/precision.py', 20765, 20808),
        ('src/melder/nexus/acl/configurations/profiles/view/safe_profile.py', 20810, 20853),
        ('src/melder/nexus/acl/frame_acl_compiled_access_surface.py', 20855, 20896),
        ('src/melder/nexus/acl/frame_acl_compiler.py', 20898, 20948),
        ('src/melder/nexus/acl/frame_acl_configuration.py', 20950, 20993),
        ('src/melder/nexus/acl/frame_acl_configuration_chain.py', 20995, 21045),
        ('src/melder/nexus/acl/frame_acl_container.py', 21047, 21108),
        ('src/melder/nexus/acl/validator/compatibility/frame_acl_set_compatibility_report.py', 21110, 21150),
        ('src/melder/nexus/acl/validator/compatibility/frame_acl_set_compatibility_validator.py', 21152, 21200),
        ('src/melder/nexus/acl/validator/frame_acl_validator.py', 21202, 21251),
        ('src/melder/nexus/acl/validator/profiles/codegen/precision_strategy.py', 21253, 21279),
        ('src/melder/nexus/acl/validator/profiles/codegen/safe_strategy.py', 21281, 21307),
        ('src/melder/nexus/acl/validator/profiles/command/precision_strategy.py', 21309, 21335),
        ('src/melder/nexus/acl/validator/profiles/command/safe_strategy.py', 21337, 21363),
        ('src/melder/nexus/acl/validator/profiles/common.py', 21365, 21383),
        ('src/melder/nexus/acl/validator/profiles/view/precision_strategy.py', 21385, 21411),
        ('src/melder/nexus/acl/validator/profiles/view/safe_strategy.py', 21413, 21439),
        ('src/melder/nexus/configuration/nexus_configuration.py', 21441, 21496),
        ('src/melder/nexus/configuration/nexus_configuration_builder.py', 21498, 21535),
        ('src/melder/nexus/configuration/nexus_frame_mode.py', 21537, 21566),
        ('src/melder/nexus/configuration/rift_access_mode.py', 21568, 21597),
        ('src/melder/nexus/configuration/rift_configuration.py', 21599, 21651),
        ('src/melder/nexus/configuration/rift_creation_mode.py', 21653, 21682),
        ('src/melder/nexus/configuration/rift_space_type.py', 21684, 21713),
        ('src/melder/nexus/configuration/rift_validation_mode.py', 21715, 21744),
        ('src/melder/nexus/frame_acl_manager.py', 21746, 21801),
        ('src/melder/nexus/frame_descriptor/conduit_descriptor_payload.py', 21803, 21847),
        ('src/melder/nexus/frame_descriptor/conduit_record.py', 21849, 21898),
        ('src/melder/nexus/frame_descriptor/frame_descriptor.py', 21900, 21952),
        ('src/melder/nexus/frame_descriptor/frame_descriptor_payload.py', 21954, 21997),
        ('src/melder/nexus/frame_descriptor/frame_record.py', 21999, 22047),
        ('src/melder/nexus/frame_descriptor/spell_descriptor_payload.py', 22049, 22092),
        ('src/melder/nexus/frame_descriptor/spell_record.py', 22094, 22142),
        ('src/melder/nexus/frame_descriptor_manager.py', 22144, 22207),
        ('src/melder/nexus/nexus.py', 22209, 22292),
        ('src/melder/nexus/nexus_frame_builder.py', 22294, 22347),
        ('src/melder/nexus/nexus_frame_configuration.py', 22349, 22404),
        ('src/melder/nexus/nexus_frame_manager.py', 22406, 22463),
        ('src/melder/nexus/rift/codegen_system/codegen_system.py', 22465, 22533),
        ('src/melder/nexus/rift/codegen_system/codegen_transaction_context.py', 22535, 22577),
        ('src/melder/nexus/rift/codegen_system/execution/codegen_compiler.py', 22579, 22619),
        ('src/melder/nexus/rift/codegen_system/execution/codegen_execution_result.py', 22621, 22662),
        ('src/melder/nexus/rift/codegen_system/execution/codegen_executor.py', 22664, 22708),
        ('src/melder/nexus/rift/codegen_system/namespace/codegen_control_surface.py', 22710, 22752),
        ('src/melder/nexus/rift/codegen_system/namespace/codegen_namespace.py', 22754, 22796),
        ('src/melder/nexus/rift/codegen_system/namespace/codegen_namespace_builder.py', 22798, 22862),
        ('src/melder/nexus/rift/codegen_system/namespace/codegen_namespace_configuration.py', 22864, 22906),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_builtins_strategy.py', 22908, 22954),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_command_strategy.py', 22956, 23001),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_control_strategy.py', 23003, 23049),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_room_objects_strategy.py', 23051, 23096),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_target_strategy.py', 23098, 23143),
        ('src/melder/nexus/rift/codegen_system/namespace/strategies/codegen_workstation_strategy.py', 23145, 23190),
        ('src/melder/nexus/rift/codegen_system/observability/codegen_event_publisher.py', 23192, 23239),
        ('src/melder/nexus/rift/codegen_system/observability/codegen_monitor.py', 23241, 23286),
        ('src/melder/nexus/rift/codegen_system/validation/codegen_validation_reporter.py', 23288, 23328),
        ('src/melder/nexus/rift/codegen_system/validation/codegen_validation_result.py', 23330, 23371),
        ('src/melder/nexus/rift/codegen_system/validation/codegen_validator.py', 23373, 23439),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_ast_structure_strategy.py', 23441, 23483),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_attribute_access_strategy.py', 23485, 23529),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_builtin_policy_strategy.py', 23531, 23575),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_import_policy_strategy.py', 23577, 23621),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_name_resolution_strategy.py', 23623, 23667),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_recursive_control_strategy.py', 23669, 23713),
        ('src/melder/nexus/rift/codegen_system/validation/strategies/codegen_reflection_policy_strategy.py', 23715, 23759),
        ('src/melder/nexus/rift/command_system/capability_command_system.py', 23761, 23806),
        ('src/melder/nexus/rift/command_system/codegen_command_system.py', 23808, 23861),
        ('src/melder/nexus/rift/command_system/command_system.py', 23863, 23916),
        ('src/melder/nexus/rift/command_system/static_command_system.py', 23918, 23962),
        ('src/melder/nexus/rift/frame_link/frame_link.py', 23964, 24006),
        ('src/melder/nexus/rift/frame_link/frame_link_contract.py', 24008, 24050),
        ('src/melder/nexus/rift/frame_viewer/frame_viewer.py', 24052, 24116),
        ('src/melder/nexus/rift/frame_viewer/static_frame_viewer.py', 24118, 24164),
        ('src/melder/nexus/rift/frame_viewer/view_action_hooks.py', 24166, 24185),
        ('src/melder/nexus/rift/frame_viewer/view_conduit.py', 24187, 24234),
        ('src/melder/nexus/rift/frame_viewer/view_frame.py', 24236, 24283),
        ('src/melder/nexus/rift/frame_viewer/view_multiframe.py', 24285, 24331),
        ('src/melder/nexus/rift/frame_viewer/view_spell.py', 24333, 24386),
        ('src/melder/nexus/rift/projection/codegen_projection.py', 24388, 24432),
        ('src/melder/nexus/rift/projection/command_projection.py', 24434, 24478),
        ('src/melder/nexus/rift/projection/frame_projection_set.py', 24480, 24528),
        ('src/melder/nexus/rift/projection/view_projection.py', 24530, 24574),
        ('src/melder/nexus/rift/rift.py', 24576, 24639),
        ('src/melder/nexus/rift/rift_gate/rift_gate.py', 24641, 24685),
        ('src/melder/nexus/rift/rift_gate_controller/rift_gate_controller.py', 24687, 24730),
        ('src/melder/nexus/rift/rift_space/capability_rift_space.py', 24732, 24777),
        ('src/melder/nexus/rift/rift_space/codegen_rift_space.py', 24779, 24828),
        ('src/melder/nexus/rift/rift_space/event_system/rift_event.py', 24830, 24863),
        ('src/melder/nexus/rift/rift_space/event_system/rift_event_system.py', 24865, 24911),
        ('src/melder/nexus/rift/rift_space/memory_system/rift_memory.py', 24913, 24945),
        ('src/melder/nexus/rift/rift_space/memory_system/rift_memory_system.py', 24947, 24993),
        ('src/melder/nexus/rift/rift_space/rift_space.py', 24995, 25056),
        ('src/melder/nexus/rift/rift_space/static_rift_space.py', 25058, 25101),
        ('src/melder/nexus/rift/rift_space/workstation.py', 25103, 25147),
        ('src/melder/system_document.py', 25149, 25187),
        ('src/melder/utilities/ai_native_support_tools/agent_text_reader.py', 25189, 25263),
        ('src/melder/utilities/ai_native_support_tools/protocol_crafter.py', 25265, 25325),
        ('src/melder/utilities/ai_native_support_tools/system_document_view.py', 25327, 25449),
        ('src/melder/utilities/caching_system/asset_cache.py', 25451, 25478),
        ('src/melder/utilities/caching_system/caching_system.py', 25480, 25540),
        ('src/melder/utilities/custom_exceptions/dead_reference_error.py', 25542, 25576),
        ('src/melder/utilities/custom_exceptions/empty_error.py', 25578, 25606),
        ('src/melder/utilities/custom_exceptions/hook_execution_error.py', 25608, 25638),
        ('src/melder/utilities/custom_exceptions/internal_registration_error.py', 25640, 25668),
        ('src/melder/utilities/custom_exceptions/meld_execution_error.py', 25670, 25699),
        ('src/melder/utilities/custom_exceptions/operation_cancelled_error.py', 25701, 25729),
        ('src/melder/utilities/custom_exceptions/phase_execution_error.py', 25731, 25766),
        ('src/melder/utilities/custom_exceptions/phase_scheduler_error.py', 25768, 25796),
        ('src/melder/utilities/custom_exceptions/phase_timeout_error.py', 25798, 25832),
        ('src/melder/utilities/custom_exceptions/spell_space_scope_error.py', 25834, 25863),
        ('src/melder/utilities/custom_exceptions/spellbook_validation_error.py', 25865, 25899),
        ('src/melder/utilities/custom_exceptions/unresolved_input_error.py', 25901, 25950),
        ('src/melder/utilities/data_structures/weak_data_structures/weak_concurrent_dict.py', 25952, 26035),
        ('src/melder/utilities/data_structures/weak_data_structures/weak_concurrent_list.py', 26037, 26087),
        ('src/melder/utilities/data_structures/weak_data_structures/weak_concurrent_set.py', 26089, 26138),
        ('src/melder/utilities/data_structures/weak_data_structures/weak_ref_node.py', 26140, 26188),
        ('src/melder/utilities/general_base/abstract_elastic_pool.py', 26190, 26239),
        ('src/melder/utilities/general_base/cleanable.py', 26241, 26309),
        ('src/melder/utilities/general_base/sync.py', 26311, 26350),
        ('src/melder/utilities/helpers/class_surface_ast_describer.py', 26352, 26426),
        ('src/melder/utilities/helpers/class_wraps.py', 26428, 26446),
        ('src/melder/utilities/helpers/general_helpers.py', 26448, 26510),
        ('src/melder/utilities/helpers/id_builder.py', 26512, 26563),
        ('src/melder/utilities/helpers/init_helpers.py', 26565, 26618),
        ('src/melder/utilities/helpers/package.py', 26620, 26676),
        ('src/melder/utilities/helpers/signature_reflection.py', 26678, 26706),
        ('src/melder/utilities/helpers/ulid_factory.py', 26708, 26742),
        ('src/melder/utilities/interfaces/ichannellogger.py', 26744, 26774),
        ('src/melder/utilities/interfaces/icleanable.py', 26776, 26806),
        ('src/melder/utilities/logger/safe_logger.py', 26808, 26860),
        ('src/melder/utilities/synchronization/cancellation_event_signal.py', 26862, 26937),
        ('src/melder/utilities/synchronization/counter_switch.py', 26939, 26991),
        ('src/melder/utilities/synchronization/creation_gate.py', 26993, 27045),
        ('src/melder/utilities/synchronization/creation_gate_controller.py', 27047, 27101),
        ('src/melder/utilities/synchronization/fast_switch.py', 27103, 27144),
        ('src/melder/utilities/synchronization/load_gate.py', 27146, 27195),
        ('src/melder/utilities/synchronization/phase_latch.py', 27197, 27240),
        ('src/melder/utilities/synchronization/phase_scheduler.py', 27242, 27316),
        ('src/melder/utilities/synchronization/safeguard.py', 27318, 27367),
        ('src/melder/utilities/synchronization/sync_weak_ref.py', 27369, 27422),
        ('src/melder/utilities/synchronization/ticket_flag.py', 27424, 27465),
        ('src/melder/utilities/synchronization/unit_of_work.py', 27467, 27523),
    ),
}
